### ISSUE TITLE
Task configuration in `README` is missleading

### ISSUE THREAD

**Issue by StefMa** [gradle/wrapper-upgrade-gradle-plugin#120]
Hello togehter 👋 

in your readme you have the section "Task configuration":
![Screenshot 2023-05-16 at 8 06 30 AM](https://github.com/gradle/wrapper-upgrade-gradle-plugin/assets/10229883/6cfabd84-52ca-49ea-beb3-ea69b0c7497b)

IMHO this is a bit of missleading. As consumers don't get in touch with *any* task here, right?
Instead, they setup the plugin extension.
So it would be rather `Extension configuration`.
But I think this is also not good.
I thought more into the direction of `Configure the plugin` or just `Configuration`...

What do you think? 🤔

**Comment by etiennestuder** [comment]
Fixed.
