### ISSUE TITLE
Do not run `wrapper` task in case there is no upgrade available

### ISSUE THREAD

**Issue by StefMa** [gradle/wrapper-upgrade-gradle-plugin#157]
I noticed that this plugin will *always* running the `wrapper` tasks, regarding of if there is an upgrade available.
However, the plugin nows already if there is an upgrade available.

https://github.com/gradle/wrapper-upgrade-gradle-plugin/blob/e60ef6bce200a2544164d054b7160c9ff51369e8/src/main/java/org/gradle/wrapperupgrade/UpgradeWrapper.java#L243-L251

Here it checks for the current release. If there is no upgrade available, it just returns *the * version (that is, `usedBuildToolVersion`).

Then it will only use *that* version to run the `wrapper` task. Whether if it is the same version or not.

https://github.com/gradle/wrapper-upgrade-gradle-plugin/blob/e60ef6bce200a2544164d054b7160c9ff51369e8/src/main/java/org/gradle/wrapperupgrade/UpgradeWrapper.java#L63-L65

https://github.com/gradle/wrapper-upgrade-gradle-plugin/blob/e60ef6bce200a2544164d054b7160c9ff51369e8/src/main/java/org/gradle/wrapperupgrade/UpgradeWrapper.java#L82-L90

I guess it makes sense to avoid this. It is an unnecessary waste of resources.
Especially since you also recommend running this periodically in the readme:

https://github.com/gradle/wrapper-upgrade-gradle-plugin/blob/e60ef6bce200a2544164d054b7160c9ff51369e8/README.md#L97

In case there is no higher version than the current version, just skip the task execution and thats it 🤷

**Comment by etiennestuder** [comment]
This is done intentionally, since rerunning the wrapper might reveal outdated script files, missing checksums, etc.

**Comment by StefMa** [comment]
But only the first run/first time, right?

We have to consider two different scenarios here.
The first is, you apply this plugin for the first time and the wrapper doesn't have an upgrade.
In this case the following could happen:
- nothing (as everything is up to date and fine) 
- build scripts might be updated, checksum etc.

All following runs will not change anything! Except there is an upgrade of course.

The second is, that you apply the plugin for the first time and the wrapper does have upgrade.
In this case, well, running the wrapper tasks make sense 🤷‍♂️ 

So as you can see, only in the first case **and**  you did something "wrong" when you added the wrapper manually, the indention behavior makes sense.
All other cases are still covered when we apply this pre-check I suggest here.

Let's imagine that it is really the case, that it fixed some build scripts. Further imagine that you run this script each week. Then you still running the wrapper task for "a long time", until Gradle do another release, without doing anything.

I just think that the intended behavior isn't necessary that important to keep it. But this is just my opinion ☺

Feel free to close this issue if I still can't convince you 🙃

**Comment by etiennestuder** [comment]
I understand what you mean. We do not intend to invest more effort into figuring out if some files need updating or not than our current mechanism does.
