### ISSUE TITLE
What permissions are required for the `WRAPPER_UPGRADE_GIT_TOKEN`

### ISSUE THREAD

**Issue by StefMa** [gradle/wrapper-upgrade-gradle-plugin#167]
The Readme states:

> create a pull request on Github, it requires a Github access token, passed with WRAPPER_UPGRADE_GIT_TOKEN environment variable.

As users don't want to give the token more permissions as needed it make sense to document which exact permissions are needed for the PAT (personal access token)

**Comment by alextu** [comment]
Thanks for reporting this! That's a good suggestion, the PAT is used to get the existing PRs on the repo and create one if needed. 
Hence that requires the "repo" scope for a classic PAT. 
For a fine grained PAT, I think just read-write permissions for "Pull requests" on the relevant repos should be fine.
I will add this infos in the README this week.
