### ISSUE TITLE
Wrapper upgrades PRs doesn't run any tests

### ISSUE THREAD

**Issue by StefMa** [gradle/wrapper-upgrade-gradle-plugin#200]
See for example this PR:
https://github.com/gradle/wrapper-upgrade-gradle-plugin/pull/188

It checks only the DCO but don't execute other tests.

This is because the PR were created by an GH Action using the build in `secrets.GITHUB_TOKEN`.
See https://github.com/gradle/wrapper-upgrade-gradle-plugin/blob/fa846e89de0c929df75400d66e42beb2c7d05062/.github/workflows/wrapper-upgrade-execution.yml#L15 and https://github.com/gradle/wrapper-upgrade-gradle-plugin/blob/fa846e89de0c929df75400d66e42beb2c7d05062/.github/workflows/wrapper-upgrade-execution.yml#L37

I guess it make sense that also the bump wrapper PRs run all of the existing tests.

To do this, one option is to provide another secret (from another user) and invite them to this repository as a collaborator with write access. Then using this secret inside the action.
The user will then create the pull requests, instead of the "GitHub Action Bot".

You might want to use your [bot-githubaction user](https://github.com/bot-githubaction) for that? 😁

**Comment by alextu** [comment]
Good catch! I was surprised to learn that and found the formal explanation https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow. 

> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs.

Another option to avoid using another token is to manually trigger the check; I think that's acceptable, given it only happens occasionally.

**Comment by StefMa** [comment]
> Another option to avoid using another token is to manually trigger the check; I think that's acceptable, given it only happens occasionally.

So in this case your actions requires an `workflow_dispatch` with an parameter for the branch to checkout.
And then your team doesn't have to forgot about it to run when there is an wrapper upgrade PR 😅 
Sorry but I guess this will not happen 😁 

I'm not sure where [this PR](https://github.com/gradle/develocity-build-config-samples/pull/1036) is comming from.
But it seems that this is working fine with the correct bot-gradle token 🤔

**Comment by alextu** [comment]
Thanks for the awareness 👍. I'm closing this for now as we prefer not to reference other tokens on this project; we'll see how it goes.
