### ISSUE TITLE
Delete the branch when PR is merged

### ISSUE THREAD

**Issue by marcusdacoregio** [gradle/wrapper-upgrade-gradle-plugin#216]
Is it possible to somehow make the plugin delete the created branch when the PR gets merged? I have a suspicion that it can only be achieved with a GitHub App.

**Comment by StefMa** [comment]
It would only be possible with some kind of a webhook 🙈. So yes, a Github app would be needed.

However there is an github setting "delete branch when merged" (or something similar). Maybe this would work for you? 🤔

**Comment by marcusdacoregio** [comment]
That option won't work for us because we do not want to delete every single branch, at least as far as I know. Maybe we can create a workflow that deletes the branches based on patterns. Thank you!
