### ISSUE TITLE
Build failed in base branch exist, but no PR with that branch is open 

### ISSUE THREAD

**Issue by StefMa** [gradle/wrapper-upgrade-gradle-plugin#252]
Right now the code checks only if there is an PR open. If so, it will omit creating a PR. Otherwise it will try to push the branch and create the PR.
However, if you close the PR but don't delete the branch (reason: you don't want to update to the latest gradle release. Therefore I close the PR, but keep the branch available. This is also how dependabot works), the build fails with "failed to push some refs to..."

**Comment by alextu** [comment]
Why would you not delete the branch, since it contains the target version 🤔 ? From what I saw in our projects, dependabot does delete the branch if you close the PR, which makes sense again since the branch name contains the dependency version.

**Comment by StefMa** [comment]
> dependabot does delete the branch if you close the PR

Oh, that is new to me.
But youre right 🙂 It does this.

> Why would you not delete the branch, since it contains the target version 🤔 ? 

Our approach is to close bump-dependencies PRs when we are not interested in them.
Dependabot can handle this (somehow).
We close the PR, dependabot replies with 
> OK, I won't notify you again about this release, but will get in touch when a new version is available. [...]
and we are good.

But we can't do the same with that plugin.
Why?
We have a scheduled GitHub Action in place that checks every week for an Wrapper Upgrade.
In case we close the PR, the GitHub Action fails with `failed to push some refs to...`.

So actually, to ignore an Wrapper Upgrade we have to keep the PR open until we have a new upgrade that superseeds that. 
And then we don't have to forget about to delete the ignored PR 😅 

Does this make sense? 

So I thought we could add a  logic to this plugin, so it checks for "branch exist" as well.
If so (and PR is closed)*then* don't do anything because the bump PR was probably by intention.

**Comment by alextu** [comment]
I see, thanks for the explanation, here's what I'm planning to implement to address this:
- Check for existing opened AND closed PR with the expected branch name.
- If found, do not recreate the PR in later runs, it's considered an ignored version
- If somehow one needs to have the PR recreated, we can add a config parameter to override this behavior, like `options.ignoreExistingPr`

**Comment by StefMa** [comment]
I guess this sounds right 👍
