### ISSUE TITLE
Running locally produces "fatal: could not read Username"

### ISSUE THREAD

**Issue by tkgregory** [gradle/wrapper-upgrade-gradle-plugin#31]
**Good work on this plugin! I'm just taking it for a spin...**

When I setup the plugin in a project.
```
plugins {
    id 'base'
    id 'org.gradle.wrapper-upgrade' version '0.10.1'
}
wrapperUpgrade {
    gradle {
        'spring-boot-api-example' {
            repo = 'tkgregory/spring-boot-api-example'
            baseBranch = 'master'
        }
    }
}
```

And run on  Ubuntu:

`WRAPPER_UPGRADE_GIT_TOKEN=<my-secret-here> ./gradlew clean upgradeGradleWrapperAll --info --stacktrace`

I get this error:
```
Starting process 'command 'git''. Working directory: /mnt/c/workspace/gradle-wrapper-update-example/build/git-clones/spring-boot-api-example Command: git push --quiet -u origin wrapperbot/spring-boot-api-example/gradle-wrapper-7.4.2
Successfully started process 'command 'git''
fatal: could not read Username for 'https://github.com/tkgregory/spring-boot-api-example.git': No such device or address
```

When I run `git push` myself from the directory and enter username/token combo it works as expected. I think the error is because Git doesn't know the username. 

**Should there be a way to specify username as well as token?** 🤔

**Comment by alextu** [comment]
Hi, you're correct, currently the token is only used for interacting with the Github API. So on our CI to setup Git creds we do:
https://github.com/gradle/android-cache-fix-gradle-plugin/blob/main/.github/workflows/wrapper-upgrade-execution.yml#L18

I wonder if it would make more sense to clone with the token in the plugin instead 🤔, @etiennestuder what do you think ?

**Comment by tkgregory** [comment]
Thanks for providing the sample workflow @alextu. 

I tried the _Set up Git configuration step_ but it now fails with this error:

> fatal: empty ident name (for <runner@fv-az407-858.a1ucnunlhxrehavgtqsuyqnora.cx.internal.cloudapp.net>) not allowed

I noticed your workflow includes importing a GPG key. Is that required to use this plugin?

**Comment by alextu** [comment]
Not really, in the snippet I sent the `crazy-max/ghaction-import-gpg` takes care of setting the proper git attributes extracted from the GPG key see https://github.com/crazy-max/ghaction-import-gpg/blob/master/src/main.ts#L109.
You should be able to get rid of the error by manually executing the git config commands as part of your Github workflow:
```
git config --global user.name "someusername"
git config --global user.email "some@email"
```

**Comment by runningcode** [comment]
@tkgregory if this is still an issue after following @alextu 's steps above, please let us know. Otherwise I will close the issue for now.
