### ISSUE TITLE
GHFileNotFoundException when trying to create PR

### ISSUE THREAD

**Issue by marcphilipp** [gradle/wrapper-upgrade-gradle-plugin#39]
I've tried this out for updating wrappers in the [junit5-samples](https://github.com/junit-team/junit5-samples) repo via a separate repo:
https://github.com/junit-team/wrapper-upgrade

However, I'm getting the following error:
https://ge.junit.org/s/ldkbyuhdhqska/console-log

**Comment by runningcode** [comment]
@marcphilipp the build scan link is not valid anymore. is the issue still happening?

**Comment by marcphilipp** [comment]
Yes, it's still happening: https://ge.junit.org/s/xk5stsji6ecg4/failure#1

**Comment by StefMa** [comment]
Does your WRAPPER_UPGRADE_GIT_TOKEN has the permission to create a PR on
the other repository? 🤔
Not sure if there are even permissions required 🤷‍♂️ just an idea...

**Comment by marcphilipp** [comment]
@StefMa Thanks, that was it. Very obvious in hindsight... 🤦‍♂️
